project_id = "yanspolqarficibgovia"

[functions.generate-card-art]
verify_jwt = false

[functions.generate-all-card-arts]
verify_jwt = false

[functions.create-demo-user]
verify_jwt = false

[functions.track-login]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.log-audit-event]
verify_jwt = true

[functions.create-notification]
verify_jwt = false

[functions.create-post-notifications]
verify_jwt = false

[functions.grant-koin-bonus]
verify_jwt = true

[functions.request-redemption]
verify_jwt = true

[functions.renew-daily-weekly-challenges]
verify_jwt = false

[functions.update-login-streaks]
verify_jwt = false

[functions.generate-school-insights]
verify_jwt = true

[functions.generate-daily-briefing]
verify_jwt = false

[functions.create-administrator]
verify_jwt = true

[functions.send-credentials-email]
verify_jwt = false

[functions.admin-password-reset]
verify_jwt = true

[functions.send-admin-welcome-email]
verify_jwt = true
